# Generated by Django 5.1.7 on 2025-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioncita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correo_electronico', models.CharField(max_length=60)),
            ],
        ),
    ]
