# Generated by Django 5.1.7 on 2025-03-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioncita', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frutas',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
